### ISSUE TITLE
Testing and using UpkieWheelsEnv gym env

### ISSUE THREAD

**Issue by perrin-isir** [tasts-robots/upkie_locomotion#11]
Hi, 
when I run `./tools/bazelisk run //agents/ppo_balancer:train`, I get:
```ModuleNotFoundError: No module named 'stable_baselines3'```

I could install it, but I thought using bazel should prevent from having to do so.

Other question: if I want to develop my own python code that would import UpkieWheelsEnv, how do I do? 
Can I use bazel to avoid having to install all the dependencies (gin-config, vulp, ...) manually?

**Comment by stephane-caron** [comment]
Thanks for mentioning it, indeed I haven't put it in [`requirements.txt`](https://github.com/tasts-robots/upkie_locomotion/blob/f5ded0b54bedb402439b2e2d92193121a8e62ad4/tools/workspace/pip_upkie_locomotion/requirements.txt).

This is a good incentive to switch to the more recent [``pip_parse``](https://github.com/bazelbuild/rules_python#installing-third_party-packages) command from Bazel's rules_python, so that SB3 and its dependencies are only downloaded [if needed](https://github.com/bazelbuild/rules_python/issues/47#issuecomment-818719047) (i.e. to run the PPO balancer; other agents don't depend on it). I've started it in https://github.com/tasts-robots/upkie_locomotion/pull/12

**Comment by stephane-caron** [comment]
> I could install it, but I thought using bazel should prevent from having to do so.

This should work now :ok_hand: 

Spinning your follow-up question in https://github.com/tasts-robots/upkie_locomotion/discussions/15.
